apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: prometheus-operator-prometheus
    tenant: b
  name: tenant-b-prometheus
  namespace: tenant-b
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: prometheus-tenants
  namespace: tenant-b
rules:
- apiGroups:
  - ""
  resources:
  - '*'
  verbs:
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: prometheus-tenant-b
  namespace: tenant-b
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-tenants
subjects:
- kind: ServiceAccount
  name: tenant-b-prometheus
  namespace: tenant-b
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    app: prometheus-operator-prometheus
    tenant: b
  name: tenant-b-prometheus
  namespace: tenant-b
spec:
  # alerting:
  #   alertmanagers:
  #   - apiVersion: v2
  #     name: cluster-monitor-prometheus-alertmanager
  #     namespace: monitoring
  #     pathPrefix: /
  #     port: web
  baseImage: quay.io/prometheus/prometheus
  enableAdminAPI: false
  externalUrl: http://tenant-b.prometheus.local/
  listenLocal: false
  logFormat: logfmt
  logLevel: info
  remoteWrite:
  - url: http://nginx-proxy-b:80/api/v1/receive
  replicas: 1
  retention: 10d
  routePrefix: /
  securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceMonitorSelector:
    matchLabels:
      app: prometheus-operator-prometheus
      tenant: b
  serviceAccountName: tenant-b-prometheus
  version: v2.18.1
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    app: prometheus-operator-prometheus
    tenant: b
  name: tenant-b-prometheus
  namespace: tenant-b
spec:
  rules:
  - host: tenant-b.prometheus.local
    http:
      paths:
      - backend:
          serviceName: tenant-b-prometheus
          servicePort: 9090
        path: /
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus-operator-prometheus
    tenant: b
    servicemonitor: default-servicemonitor
    monitor: "true"
  name: tenant-b-prometheus
  namespace: tenant-b
spec:
  ports:
  - name: web
    port: 9090
    protocol: TCP
    targetPort: web
  selector:
    app: prometheus
    prometheus: tenant-b-prometheus
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: prometheus-operator-prometheus
    tenant: b
  name: default-servicemonitor
  namespace: tenant-b
spec:
  endpoints:
  - port: web
    path: /metrics
  namespaceSelector:
    matchNames:
    - tenant-b
  selector:
    matchLabels:
      servicemonitor: default-servicemonitor
      monitor: "true"